name: CI

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - main

jobs:
  clippy:
    name: "(${{ matrix.os }}) Lint with clippy"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: windows-latest }
          - { os: ubuntu-latest }
    env:
      RUSTFLAGS: -Dwarnings
    steps:
      - name: Ensure windows git checkout keeps \n line ending
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf
        if: matrix.os == 'windows-latest'
      - name: Install PAM devel (Linux)
        run: sudo apt install -y libpam0g-dev
        if: matrix.os == 'ubuntu-latest'
      - uses: actions/checkout@v3
      - name: Install Rust (clippy)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Check Cargo availability
        run: cargo --version
      - name: Clippy check
        run: cargo clippy --verbose --all-features
  rustfmt:
    name: "(${{ matrix.os }}) Verify code formatting"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: windows-latest }
          - { os: ubuntu-latest }
    steps:
      - name: Ensure windows git checkout keeps \n line ending
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf
        if: matrix.os == 'windows-latest'
      - name: Install PAM devel (Linux)
        run: sudo apt install -y libpam0g-dev
        if: matrix.os == 'ubuntu-latest'
      - uses: actions/checkout@v3
      - name: Install Rust (rustfmt)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Check Cargo availability
        run: cargo --version
      - run: cargo fmt --all -- --check
  tests:
    name: "(${{ matrix.os }}) Test Rust ${{ matrix.rust }} ${{ matrix.target }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { rust: stable, os: windows-latest }
          - { rust: stable, os: macos-latest }
          - { rust: stable, os: ubuntu-latest }
          - { rust: 1.64.0, os: ubuntu-latest }
    steps:
      - name: Install PAM devel (Linux)
        run: sudo apt install -y libpam0g-dev
        if: matrix.os == 'ubuntu-latest'
      - uses: actions/checkout@v3
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      - name: Generate randoms
        uses: joellefkowitz/random-env@v1.0.0
        with:
          names: |
            RANDOM_VALUE
      - name: Set test username & password
        shell: bash
        run: |
          echo "PWCHECK_TEST_USERNAME=testuser" >> "$GITHUB_ENV"
          echo "PWCHECK_TEST_PASSWORD=testpass_${{ env.RANDOM_VALUE }}" >> "$GITHUB_ENV"
      - name: Create a test account (Linux)
        run: |
          sudo useradd -m ${{ env.PWCHECK_TEST_USERNAME }}
          echo "${{ env.PWCHECK_TEST_USERNAME }}:${{ env.PWCHECK_TEST_PASSWORD }}" | sudo chpasswd
        if: matrix.os == 'ubuntu-latest'
      - name: Create a test account (MacOS)
        run: |
          sudo sysadminctl -addUser "${{ env.PWCHECK_TEST_USERNAME }}" -password "${{ env.PWCHECK_TEST_PASSWORD }}"
        if: matrix.os == 'macos-latest'
      - name: Create a test account (Windows)
        run: |
          net user /Y /add "${{ env.PWCHECK_TEST_USERNAME }}" "${{ env.PWCHECK_TEST_PASSWORD }}"
        if: matrix.os == 'windows-latest'
      - name: Run tests (MacOS/Windows)
        run: cargo test --release --all-features
        if: matrix.os != 'ubuntu-latest'
      - name: Run tests as testuser (Linux)
        run: |
          sudo -u ${{ env.PWCHECK_TEST_USERNAME }} curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain ${{ matrix.rust }}
          sudo -u ${{ env.PWCHECK_TEST_USERNAME }} bash -c ". \"$HOME/.cargo/env\" && cargo test --release --all-features"
        if: matrix.os == 'ubuntu-latest'
